// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpmGoGt2QDnfjUDwiMFLC4LxnkGeRgdxU',
    appId: '1:1018931014748:web:fd16f9193dea7a0af5ca99',
    messagingSenderId: '1018931014748',
    projectId: 'pidi-b580e',
    authDomain: 'pidi-b580e.firebaseapp.com',
    storageBucket: 'pidi-b580e.appspot.com',
    measurementId: 'G-3PR13R8LQ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAcIQzqmWFXYRDMRISV97_DWhjjZ-to4aY',
    appId: '1:1018931014748:android:43abf503cd680390f5ca99',
    messagingSenderId: '1018931014748',
    projectId: 'pidi-b580e',
    storageBucket: 'pidi-b580e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCsFJAwXoqo5ODKa5Lo8odNadVo7hHr9nI',
    appId: '1:1018931014748:ios:6416241788c1584ef5ca99',
    messagingSenderId: '1018931014748',
    projectId: 'pidi-b580e',
    storageBucket: 'pidi-b580e.appspot.com',
    iosClientId:
        '1018931014748-ha0kik5b05gse7o07cfbp71vas5t7v6j.apps.googleusercontent.com',
    iosBundleId: 'com.example.pidi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCsFJAwXoqo5ODKa5Lo8odNadVo7hHr9nI',
    appId: '1:1018931014748:ios:6416241788c1584ef5ca99',
    messagingSenderId: '1018931014748',
    projectId: 'pidi-b580e',
    storageBucket: 'pidi-b580e.appspot.com',
    iosClientId:
        '1018931014748-ha0kik5b05gse7o07cfbp71vas5t7v6j.apps.googleusercontent.com',
    iosBundleId: 'com.example.pidi',
  );
}
